default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25

development:
  <<: *default
  port: 5432
  database: bulk_uploader_development
  username: postgres
  password: 123456
  host: localhost
